### ISSUE TITLE
Assertion thrown for is_in when checking a list of dictionaries

### ISSUE THREAD

**Issue by Fongeme** [assertpy/assertpy#113]
example:
``` python
>>> from assertpy import assert_that
>>> d = {'This is a dictionary': 'Some value'}
>>> assert_that(d).is_in([d])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yair/.virtualenvs/sqa/lib/python3.8/site-packages/assertpy/contains.py", line 336, in is_in
    self.error('Expected <%s> to be in %s, but was not.' % (self.val, self._fmt_items(items)))
  File "/home/yair/.virtualenvs/sqa/lib/python3.8/site-packages/assertpy/assertpy.py", line 433, in error
    raise AssertionError(out)
AssertionError: Expected <{'This is a dictionary': 'Some value'}> to be in <[{'This is a dictionary': 'Some value'}]>, but was not.
```

**Comment by Fongeme** [comment]
Apperently it shouldve been
```
assert_that(d).is_in(*[d])
```
